[workspace]
resolver = "2"
members = [
  "crates/obs-sys",
  "crates/styledcamera-core",
  "crates/styledcamera",
]

[workspace.package]
version = "0.1.2"
edition = "2021"
license = "GPL-2.0-or-later"
